version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ..
      dockerfile: ops/docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./data.db
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DEBUG=true
      - ALERTS_ENABLED=true
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-gopalakrishnan.kuppan@gmail.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-your-app-password}
    volumes:
      - ./data:/app/data
      - ../backend:/app
    working_dir: /app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on: []

  # Frontend development service
  frontend:
    build:
      context: ../frontend
      dockerfile: ../ops/docker/frontend.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000
    volumes:
      - ../frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    depends_on:
      - backend

  # Background worker service
  worker:
    build:
      context: ..
      dockerfile: ops/docker/worker.Dockerfile
    environment:
      - ENABLE_GH=${ENABLE_GH:-true}
      - ENABLE_JENKINS=${ENABLE_JENKINS:-false}
      - WORKER_POLL_INTERVAL=${WORKER_POLL_INTERVAL:-60}
      - WORKER_JITTER_SECONDS=${WORKER_JITTER_SECONDS:-10}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-your-github-token}
      - GITHUB_REPOS=${GITHUB_REPOS:-nandhu-devops/cicd-pipeline-dashboard}
      - DASHBOARD_API_URL=http://backend:8000
      - DASHBOARD_API_KEY=${DASHBOARD_API_KEY:-dev-write-key-change-in-production}
    volumes:
      - ../worker:/app
    working_dir: /app
    command: ["python", "run_scheduler.py"]
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*scheduler.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
    driver: local
